const GET_TOKEN = "GET_TOKEN";
const ADD_TOKEN = "ADD_TOKEN";
const GETTING_TOKEN = "GETTING_TOKEN";
const LOADING_PROJECTS = "LOADING_PROJECTS";
const ADD_PROJECTS = "ADD_PROJECTS";

export { GET_TOKEN, GETTING_TOKEN, ADD_TOKEN, LOADING_PROJECTS, ADD_PROJECTS };
