const GET_TOKEN = "GET_TOKEN";
const ADD_TOKEN = "ADD_TOKEN";
const GETTING_TOKEN = "GETTING_TOKEN";
const LOADING_PROJECTS = "LOADING_PROJECTS";
const ADD_PROJECTS = "ADD_PROJECTS";
const LOGGING_IN = "LOGGING_IN";
const LOG_IN = "LOG_IN";
const LOG_OUT = "LOG_OUT";
const ADD_MY_PROJECTS = "ADD_MY_PROJECTS";

export {
  GET_TOKEN,
  GETTING_TOKEN,
  ADD_TOKEN,
  LOADING_PROJECTS,
  ADD_PROJECTS,
  LOGGING_IN,
  LOG_IN,
  LOG_OUT,
  ADD_MY_PROJECTS
};
